### PR TITLE
v0.6 @Magitechteam w/ a website

### PR DESCRIPTION
**Pull request by JustThePacksTeam**

### CODE REVIEW

**Comment by JustThePacksTeam** [comment]
Still working on

**Comment by JustThePacksTeam** [comment]
All set when u are

**Comment by JustThePacksTeam** [comment]
Btw i didnt remove Animatia : typo on my part

**Comment by AjaxVM** [comment]
Cool! Thanks for the changes.
Unfortunately I missed the email for this, apologies for taking so long to look at it.

Some of this is not quite the direction I was taking (ie, remove treechopper without replacing to favor tinkers tools).
But I am very interested in the world gen. Would you mind rebasing your branch off my 0.6 (that fixes some key issues)?

Basically - I would love to try out your changes for the world gen. I am not sure about Dungeons2 or Player Skin Mobs (typo in your changelog?)

What do you think about limiting this to MistBiomes and Recurrent Complex (really interested if you delagged it enough) for now?
I would add Ruins to that list but it is not visible on curse yet, and I am holding back from adding mods that way (even if it is possible) until later versions.

**Comment by AjaxVM** [comment]
I am about to push 0.6 already, so this would be a good start to 0.7 if you would like to retag it as such?

**Comment by JustThePacksTeam** [comment]
Cool u can push it. Ill push the website seprately

**Comment by JustThePacksTeam** [comment]
And BTW I added TreeCapicaton in that

And BTW the Ruins mod as long as u drop in the file from the minecraft.curseforge.com website it WONT go into overides

**Pull request closed without merging**
